name: 'augemented reality setup'
model: 'Intel RealSense L515'
serial_number: "f1320305"

channels:

  - #<-this is first entry in the channels list
    type: depth
    fps: 30
    buffer_length: 30

  - #<-this is second entry in the channels list
    type: color
    fps: 30
    buffer_length: 30

  - 
    type: infrared
    fps: 30
    buffer_length: 30

  - 
    type: accel
    fps: 200
    buffer_length: 30000

  - 
    type: gyro
    fps: 400
    buffer_length: 30000